### ISSUE TITLE
Can't install properly

### ISSUE THREAD

**Issue by AviatorBimmer** [vectronic/homebridge-jvc-projector#6]
Hello all, I am trying to install this on my Homebridge setup but I can't get past the step to install this:

pip install -e git+https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote

It keeps giving me an error within the Terminal:

bash-5.1# pip install -e git+https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote
Obtaining jvc-projector-remote from git+https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/vcs/git.py", line 331, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 100, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 306, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 155, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 324, in __init__
    super(EditableCandidate, self).__init__(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 335, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/usr/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 573, in prepare_editable_requirement
    req.update_editable(self.download_dir is None)
  File "/usr/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 655, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "/usr/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py", line 560, in obtain
    existing_url = self.get_remote_url(dest)
  File "/usr/lib/python3.9/site-packages/pip/_internal/vcs/git.py", line 333, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

Can anyone please help me?

**Comment by vectronic** [comment]
Do you have `git` installed? 

Can your machine reach GitHub? e.g.: `curl https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote`

**Comment by AviatorBimmer** [comment]
> Do you have `git` installed?
> 
> Can your machine reach GitHub? e.g.: `curl https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote`

Hi Vectronic,

When I execute that curl URL, I get the following message:

```
bash-5.1# curl https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1><301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Not sure if I have git installed. If I don't, how do I install it via the Homebridge's Terminal?

**Comment by vectronic** [comment]
The access check via curl looks ok.

To check if `git` is installed type `git`. If it isn't you will have to ask Google how to install it.

**Comment by AviatorBimmer** [comment]
I ran git and it says I have version 2.34.2 installed. I guess I do have git installed.
